### ISSUE TITLE
Syntax Highlighting in strings (C)

### ISSUE THREAD

**Issue by zivkaplan** [k3a/theme-darkplus-contrast#1]
HI!
I enjoy your theme very much! 

One thing that I would like to point is that it would be useful to have a different color/shade for special characters inside string.
Escape character and others. 

screenshot example:
![image](https://user-images.githubusercontent.com/80772683/151179171-b1580828-0493-4944-9f29-d25b0f31e225.png)

I am beginner programmer, hopefully I am not doing anything wrong.
Let me know if I can contribute and help!

**Comment by k3a** [comment]
I updated the theme to the [master](https://github.com/microsoft/vscode) and this is now fixed in [v1.76.0](https://github.com/k3a/theme-darkplus-contrast/releases/tag/v1.76.0)!
Sorry that it took more than a year but this had low priority.

**Comment by zivkaplan** [comment]
Amazing! Thanks :)
